In [ ]:
#NumPy stands for Numerical Python, is an open-source Python library that provides support for large, multi-dimensional arrays and matrices.


In [ ]:
#Install Python NumPy:

pip install numpy

In [7]:
#The shape of an array can be defined as the number of elements in each dimension. 
# Dimension is the number of indices or subscripts, that we require in order to specify an individual element of an array.

import numpy as npy

# creating a 2-d array
arr1 = npy.array([[1, 3, 5, 7], [2, 4, 6, 8]])

# creating a 3-d array
arr2 = npy.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr1.shape)
print(arr2.shape)


(2, 4)
(2, 2, 2)


In [8]:
# In Python, numpy.size() function count the number of elements along a given axis.
# Python program explaining
# numpy.size() method 

# importing numpy 
import numpy as np

# Making a random array 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# By default, give the total number of elements.
print(np.size(arr))


8


In [9]:
#Every ndarray has an associated data type (dtype) object. This data type object (dtype) informs us about the layout of the array.
# Constructing a data type (dtype) object:

# Python program to demonstrate
# the use of data type object with structured array.
import numpy as np

dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))])

# x is a structured array with names and marks of students.
# Data type of name of the student is np.unicode_ and
# data type of marks is np.float(64)
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))], dtype=dt)

print(x[1])
print("Grades of John are: ",x[1]['grades'])
print("Names are: ",x['name'])


('John', [6., 7.])
Grades of John are:  [6. 7.]
Names are:  ['Sarah' 'John']


In [10]:
# Data type Objects with Structured Arrays:Data type objects are useful for creating structured arrays

# Python program for demonstrating 
# the use of fields
import numpy as np

# A structured data type containing a 16-character string (in field ‘name’)
# and a sub-array of two 64-bit floating-point number (in field ‘grades’):

dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))])

# Data type of object with field grades
print(dt['grades'])

# Data type of object with field name
print(dt['name'])


('<f8', (2,))
<U16


In [13]:
# Operations on Numpy Arrays:

#Arithmetic Operations: 
# Python code to perform arithmetic
# operations on NumPy array


import numpy as np 


# Initializing the array
arr1 = np.arange(4, dtype = np.float_).reshape(2, 2) 

print('First array:') 
print(arr1)

print('\nSecond array:') 
arr2 = np.array([12, 12]) 
print(arr2)

print('\nAdding the two arrays:') 
print(np.add(arr1, arr2))

print('\nSubtracting the two arrays:') 
print(np.subtract(arr1, arr2))

print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))

print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))




First array:
[[0. 1.]
 [2. 3.]]

Second array:
[12 12]

Adding the two arrays:
[[12. 13.]
 [14. 15.]]

Subtracting the two arrays:
[[-12. -11.]
 [-10.  -9.]]

Multiplying the two arrays:
[[ 0. 12.]
 [24. 36.]]

Dividing the two arrays:
[[0.         0.08333333]
 [0.16666667 0.25      ]]


In [14]:
#numpy.reciprocal() 

# Python code to perform reciprocal operation
# on NumPy array
import numpy as np 
arr = np.array([25, 1.33, 1, 1, 100]) 

print('Our array is:')
print(arr)

print('\nAfter applying reciprocal function:') 
print(np.reciprocal(arr))

arr2 = np.array([25], dtype = int)
print('\nThe second array is:')
print(arr2)

print('\nAfter applying reciprocal function:') 
print(np.reciprocal(arr2))


Our array is:
[ 25.     1.33   1.     1.   100.  ]

After applying reciprocal function:
[0.04      0.7518797 1.        1.        0.01     ]

The second array is:
[25]

After applying reciprocal function:
[0]


In [15]:
#numpy.power()

# Python code to perform power operation
# on NumPy array


import numpy as np 


arr = np.array([5, 10, 15]) 

print('First array is:') 
print(arr)

print('\nApplying power function:') 
print(np.power(arr, 2))

print('\nSecond array is:') 
arr1 = np.array([1, 2, 3]) 
print(arr1)

print('\nApplying power function again:') 
print(np.power(arr, arr1))


First array is:
[ 5 10 15]

Applying power function:
[ 25 100 225]

Second array is:
[1 2 3]

Applying power function again:
[   5  100 3375]


In [16]:
#numpy.mod()

# Python code to perform mod function
# on NumPy array


import numpy as np 


arr = np.array([5, 15, 20]) 
arr1 = np.array([2, 5, 9]) 

print('First array:') 
print(arr) 

print('\nSecond array:') 
print(arr1)

print('\nApplying mod() function:') 
print(np.mod(arr, arr1))

print('\nApplying remainder() function:') 
print(np.remainder(arr, arr1))


First array:
[ 5 15 20]

Second array:
[2 5 9]

Applying mod() function:
[1 0 2]

Applying remainder() function:
[1 0 2]


In [17]:
#Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops. 
# This is because NumPy is implemented in C Programming, which is a very efficient language.

#Array Element-wise Multiplication
import numpy as np 

a = np.array([5, 7, 3, 1]) 
b = np.array([90, 50, 0, 30]) 

# array are compatible because of same Dimension 
c = a * b 
print(c) 


[450 350   0  30]


In [19]:
#NumPy Broadcasting Arrays in Python
#Example: Broadcasting Array- Element Wise Multiplication

macros = array([ 
[0.8, 2.9, 3.9], 
[52.4, 23.6, 36.5], 
[55.2, 31.7, 23.9], 
[14.4, 11, 4.9] 
]) 

result = zeros_like(macros) 

cal_per_macro = array([3, 3, 8]) 

for i in range(macros.shape[0]): 
	result[i, :] = macros[i, :] * cal_per_macro 

result 

result 


NameError: name 'array' is not defined

In [22]:
#Array Broadcasting Algorithm
p = max(m, n)
if m < p:
    left-pad A's shape with 1s until it also has p dimensions
else if n < p:
    left-pad B's shape with 1s until it also has p dimensions
result_dims = new list with p elements
for i in p-1 ... 0:
    A_dim_i = A.shape[i]
    B_dim_i = B.shape[i]
    if A_dim_i != 1 and B_dim_i != 1 and A_dim_i != B_dim_i:
        raise ValueError("could not broadcast")
    else:
        # Pick the Array which is having maximum Dimension
        result_dims[i] = max(A_dim_i, B_dim_i) 

SyntaxError: unterminated string literal (detected at line 4) (682347012.py, line 4)

In [23]:
#Array Broadcasting of Two-Dimensional Array  
import numpy as np 
A = np.array([[11, 22, 33], [10, 20, 30]]) 
print(A) 

b = 4
print(b) 

C = A + b 
print(C)


[[11 22 33]
 [10 20 30]]
4
[[15 26 37]
 [14 24 34]]


In [25]:
#NumPy Broadcasting Operations
import numpy as np 

v = np.array([1, 2, 3]) 
w = np.array([4, 5])	 

# Outer product of vectors v and w 
print(np.reshape(v, (3, 1)) * w) 

x = np.array([[1, 2, 3], [4, 5, 6]]) 

# Broadcasting vector v to matrix x 
print(x + v) 

# Broadcasting vector w to the transposed matrix x 
print((x.T + w).T) 

# Reshaping vector w and broadcasting to matrix x 
print(x + np.reshape(w, (2, 1))) 

# Broadcasting scalar multiplication to matrix x 
print(x * 2) 


[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


In [27]:
#Rules for Broadcasting
#Broadcasting arrays is possible if the following rules are met: 

#If the arrays don’t have the same rank then prepend the shape of the lower rank array with 1s until both shapes have the same length.
#The two arrays are compatible in a dimension if they have the same size in the dimension or if one of the arrays has size 1 in that dimension.
#The arrays can be broadcast together if they are compatible with all dimensions.
#After broadcasting, each array behaves as if it had a shape equal to the element-wise maximum of shapes of the two input arrays.
#In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.

In [28]:
#Basic Slicing and Advanced Indexing in NumPy
#Indexing a NumPy array means accessing the elements of the NumPy array at the given index.
#There are two types of indexing in NumPy: basic indexing and advanced indexing.
#Indexing Using Index arrays:
import numpy as np 
# Create a sequence of integers from 10 to 1 with a step of -2 
a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a) 
# Indexes are specified inside the np.array method. 
newarr = a[np.array([3, 1, 2 ])] 
print("\n Elements at these indices are:\n",newarr)



 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [29]:
#Advanced indexing
#NumPy Advanced indexing returns a copy of data rather than a view of it. Advanced indexing is of two types integer and Boolean.

#There are two types of Advanced Indexing in NumPy array indexing:

#Purely integer indexing
#Boolean integer indexing

#Purely integer array indexing
#Purely integer array indexing allows us to access elements from an ndarray (N-dimensional array) using integers
# Python program showing advanced indexing 
import numpy as np 
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]]) 
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])



[1 3 6]


In [30]:
#Boolean Indexing 
#This indexing has some boolean expressions as the index.

#Those elements are returned which satisfy that Boolean expression. It is used for filtering the desired element values.
# You may wish to select numbers greater than 50 
import numpy as np 

a = np.array([10, 40, 80, 50, 100]) 
print(a[a>50])


[ 80 100]


In [38]:
#Basic Slicing and indexing
#Basic slicing and indexing is used to access a specific element or range of elements from a NumPy array.
import numpy as np 
# A 3 dimensional array. 
b = np.array([[[1, 2, 3],[4, 5, 6]], 
			[[7, 8, 9],[10, 11, 12]]]) 
print(b[...,1]) #Equivalent to b[: ,: ,1 ]




[[ 2  5]
 [ 8 11]]


In [41]:
#1. Reshaping Arrays
#Reshaping an array means changing its shape without changing its data. This is useful when you want to convert the array into a different dimension.

#Example:
import numpy as np

# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping the array to 2x3
reshaped_arr = arr.reshape((2, 3))
print("Reshaped Array:\n", reshaped_arr)


Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [43]:
#2. Flattening Arrays
#Flattening an array means converting a multi-dimensional array into a one-dimensional array. This can be useful when you need a single list of elements.

#Example:
# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Flattening the array
flattened_arr = arr.flatten()
print("Flattened Array:", flattened_arr)


Flattened Array: [1 2 3 4 5 6]


In [44]:
#3. Concatenating Arrays
#Concatenation involves combining multiple arrays into one. NumPy provides functions like np.concatenate, np.vstack, and np.hstack for this purpose.

#Example:
# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenating the arrays along the first axis
concatenated_arr = np.concatenate((arr1, arr2))
print("Concatenated Array:", concatenated_arr)

# Creating two 2D arrays
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

# Vertical concatenation
vstacked_arr = np.vstack((arr3, arr4))
print("Vertically Stacked Array:\n", vstacked_arr)

# Horizontal concatenation
hstacked_arr = np.hstack((arr3, arr4))
print("Horizontally Stacked Array:\n", hstacked_arr)


Concatenated Array: [1 2 3 4 5 6]
Vertically Stacked Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally Stacked Array:
 [[1 2 5 6]
 [3 4 7 8]]


In [46]:
#Stacking Arrays
# np.vstack
#np.vstack is used to stack arrays vertically (row-wise).
import numpy as np

# Creating two 2D arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

# Vertically stacking arrays
vstacked = np.vstack((a, b))
print("Vertical Stack:\n", vstacked)


Vertical Stack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [47]:
# np.stack
#np.stack joins a sequence of arrays along a new axis. The axis parameter specifies the index of the new axis in the dimensions of the result.
# Stacking arrays along a new axis
stacked = np.stack((a, b), axis=0)
print("Stack along new axis (axis=0):\n", stacked)


Stack along new axis (axis=0):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [48]:
# np.hstack
#np.hstack is used to stack arrays horizontally (column-wise).

# Horizontally stacking arrays
hstacked = np.hstack((a, b))
print("Horizontal Stack:\n", hstacked)


Horizontal Stack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [49]:
#Splitting Arrays
#np.split
#np.split divides an array into multiple sub-arrays along a specified axis.
# Splitting array into 2 equal sub-arrays
splitted = np.split(a, 2)
print("Split into 2 sub-arrays:\n", splitted)


Split into 2 sub-arrays:
 [array([[1, 2, 3]]), array([[4, 5, 6]])]


In [50]:
# np.vsplit
#np.vsplit splits an array into multiple sub-arrays vertically (row-wise).
# Splitting array vertically into 2 sub-array
vsplitted = np.vsplit(a, 2)
print("Vertical Split:\n", vsplitted)


Vertical Split:
 [array([[1, 2, 3]]), array([[4, 5, 6]])]


In [52]:
#3. np.hsplit
#np.hsplit splits an array into multiple sub-arrays horizontally (column-wise).
# Splitting array horizontally into 3 sub-arrays
hsplitted = np.hsplit(a, 3)
print("Horizontal Split:\n", hsplitted)


Horizontal Split:
 [array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [53]:
#adding and removing elemts
#1. Appending Elements
#WE can use the numpy.append function to append elements to an array. 
# It returns a new array with the values appended to the end.
import numpy as np

arr = np.array([1, 2, 3])
new_arr = np.append(arr, [4, 5, 6])
print(new_arr)


[1 2 3 4 5 6]


In [55]:
#2. Inserting Elements
#WE can use the numpy.insert function to insert values into an array at specified indices.
import numpy as np

arr = np.array([1, 2, 3])
new_arr = np.insert(arr, 1, [4, 5])
print(new_arr)


[1 4 5 2 3]


In [56]:
#3. Deleting Elements
#we  can use the numpy.delete function to remove elements from an array at specified indices.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
new_arr = np.delete(arr, [1, 3])
print(new_arr)


[1 3 5]
